### ISSUE TITLE
Never finishes

### ISSUE THREAD

**Issue by lastmjs** [zumwald/oss-attribution-generator#2]
This is just what I needed! I've been waiting to use use yarn for all of our dependencies for certain reasons, and it has an automatic attribution generator. But this is perfect for what we need in the mean time because it supports bower. I've gotten the bower_components attribution to generate just fine, but the node_modules attribution never finishes. Its last output is:
```
processing zwitterion-production@0.0.5
```

**Comment by lastmjs** [comment]
So, I removed that dependency and everything seemed to work...is there something wrong with `zwitterion-production`'s package.json? https://github.com/lastmjs/zwitterion-production/blob/master/package.json

**Comment by zumwald** [comment]
I've created a branch with some additional logging for you to try out - but I'm seeing the same thing you are. It seems to be something with how the modules are laid out in the file system, as the "hang" happens at line 94. If you're able to dig a little deeper in what the rogue package is in your project I'd be happy to fix.

**Comment by zumwald** [comment]
https://github.com/zumwald/oss-attribution-generator/tree/add-debugging-for-2

**Comment by martinzuern** [comment]
Same happens for me at package `yargs@3.10.0`

**Comment by martinzuern** [comment]
Still happens, this time it's `processing winston@2.3.1`
