### ISSUE TITLE
feature request: allow multiple project folders as input

### ISSUE THREAD

**Issue by Kyle-Falconer** [zumwald/oss-attribution-generator#6]
Currently, this program accepts two command-line arguments, one for the output directory (where the attribution text will be saved), and one for the input directory (the path to the Node.js project). It would be very useful to accept a variable number of input directories.

Each of the input directories passed in with the `-b` argument would processed, and duplicate entries (dependencies with same name and version number) would be combined to produce a smaller attribution text and prevent having to manually combine multiple attribution texts if the program had been run separately on the various Node.js projects.

Example usage:

```
cd pathToYourMainProject
generate-attribution -b pathToYourMainProject pathToYourFirstProjectDependency pathToYourSecondProjectDependency
git add ./oss-attribution
git commit -m 'adding open source attribution output from oss-attribution-generator'
```

**Comment by zumwald** [comment]
merged

**Comment by Kyle-Falconer** [comment]
Thanks for merging in this change, @zumwald.

Do you mind also publishing this revision to npm?

**Comment by zumwald** [comment]
1.4.0 is published now :)

**Comment by absolutehype** [comment]
Does this appear to work for everyone? I'm getting `unable to locate package.json`
